- name: Create Azure VM
  hosts: remoteVM
  gather_facts: yes
  become: yes
  vars:
    ansible_ssh_user: azureuser
  tasks:
    - name: copying file with playbook
      become: true 
      copy:
        src: /Powershell_Scripts/TechChallengeApp/lib/deploy.sh
        dest: /home/azureuser
        owner: azureuser
        group: azureuser        
        mode: 0644
    - name: deploy the application in Azure VM
      environment:
        host_ip: 20.124.194.162 
      shell: |
        chmod 755 /home/azureuser/deploy.sh
        cd /home/azureuser/
        ./deploy.sh
