- name: Starting the Azure Deployment play
  hosts: localhost
  connection: local
  tasks:
    - name: Include Vars | Initialize global vars file
      include_vars:
        file: "vars.yaml"

    - name: 'Block | Starting to build VM!'
      block:
        - name: 'Create resource group'
          azure_rm_resourcegroup:
            name: "{{ general.resourcegroup_name }}"
            location: "{{ general.location }}"

        - name: 'Create virtual network'
          azure_rm_virtualnetwork:
            resource_group: "{{ general.resourcegroup_name }}"
            name: "{{ general.vmnet_name }}"
            address_prefixes: "{{ general.vmnet_address_prefix }}"

        - name: 'Add subnet'
          azure_rm_subnet:
            resource_group: "{{ general.resourcegroup_name }}"
            name: "{{ general.vmnet_subnet_name }}"
            address_prefix: "{{ general.subnet_address_prefix }}"
            virtual_network: "{{ general.vmnet_name }}"

        - name: 'Create public IP address'
          azure_rm_publicipaddress:
            resource_group: "{{ general.resourcegroup_name }}"
            allocation_method: Static
            name: myPublicIP
          register: output_ip_address

        - name: 'Public IP of VM'
          debug:
            msg: "The public IP is {{ output_ip_address.state.ip_address }}."

        - name: 'Create Network Security Group that allows SSH'
          azure_rm_securitygroup:
            resource_group: "{{ general.resourcegroup_name }}"
            name: "{{ general.network_security_group_name }}"
            rules:
              - name: custom
                protocol: Tcp
                destination_port_range:
                   - 22
                   - 80
                   - 443
                   - 3000
                access: Allow
                priority: 1001
                direction: Inbound
              - name: Postgres
                protocol: Tcp
                destination_port_range: 5482
                access: Allow
                priority: 1002
                direction: Outbound

        - name: 'Create virtual network interface card'
          azure_rm_networkinterface:
            resource_group: "{{ general.resourcegroup_name }}"
            name: myNIC
            virtual_network: "{{ general.vmnet_name }}"
            subnet: "{{ general.vmnet_subnet_name }}"
            public_ip_name: myPublicIP
            security_group: "{{ general.network_security_group_name }}"

        - name: 'Create VM'
          azure_rm_virtualmachine:
            resource_group: "{{general.resourcegroup_name}}"
            name: "{{ virtual_machine.vm_name }}"
            vm_size: "{{ virtual_machine.vm_size }}"
            admin_username: "{{ virtual_machine.admin_username }}"
            ssh_password_enabled: false
            ssh_public_keys:
              - path: /home/azureuser/.ssh/authorized_keys
                key_data: "{{ virtual_machine.ssh_public_keys }}"
            network_interfaces: myNIC
            image:
              offer: "{{ virtual_machine.offer }}"
              publisher: "{{ virtual_machine.publisher }}"
              sku: "{{ virtual_machine.sku }}"
              version: "{{ virtual_machine.version }}"

      when: "{{ general.deploy_vm }} == true"
